Friday bugs should be a part of the Monday triage
If ustriage is run on a Saturday, it'd result in the
following traceback:
```
day = ['Tuesday', 'Wednesday', 'Thursday', 'Friday'][start_weekday]
IndexError: list index out of range
```
because it looks for bugs on Friday, which should
essentially be a part of the Monday triage.

Signed-off-by: Utkarsh Gupta <utkarsh@debian.org>