core22: set python path
Without this core22 would hit:
  ModuleNotFoundError: No module named 'yaml'

Inspired from more mature core22 python snaps like MAAS which had
this set as well [1]. There and in many others it was added with
core20 and carried since.

[1]: https://github.com/maas/maas/blob/master/snap/snapcraft.yaml#L26

Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>