core22: switch to core22
When based on core18 it started to hit ssl issues when talking to
launchpad, like:
  ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert
  protocol version (_ssl.c:852)

This can be reproduced in `snap run --shell ustriage` but not in a
bionic lxd system. While it could be debugged and fixed inside core18,
bumping this up is good overall.

Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>